[engine]
rate = 20
duration = "20s"
cap = 4

[client]
script = "benchmark/ethereum/invoke/script.lua"     # 脚本
type = "eth"                                        # 区块链类型
contract = "benchmark/ethereum/invoke/contract"     # 合约目录路径
config = "benchmark/ethereum/invoke/eth"            # 区块链SDK配置路径
plugin = "./eth.so"                                 # 插件路径
args = ["1.0"]                                      # 合约参数路径

[client.options] # 客户端选项

[recorder.log]
dump=false
dir="./logs"
level="debug"

[recorder.csv]
dir="./csv"





