[engine]
rate = 1                        # 速率，重点压测指标
duration = "10s"                # 持续时间
cap = 2                         # 客户端虚拟机数量，类似CPU核心数
accounts = 1000                 # 总账户数

# uniswap 稳定性测试配置
[client]
script = "benchmark/ethereum/uniswap/script.lua"     # 脚本
type = "eth"                                         # 区块链类型
contract = "benchmark/ethereum/uniswap/contract"     # 合约目录
contract_num = 1                                     # 合约部署数量
config = "benchmark/ethereum/uniswap/eth"            # 区块链SDK配置路径
plugin = "./eth.so"                                  # 插件路径
args = []

[client.options] # 客户端选项

[recorder.log]
dump=false
dir="./logs"
level="debug"

[recorder.csv]
dir="./csv"





