[engine]
rate = 20                                   # 速率
duration = "20s"                            # 持续时间
cap = 10                                    # 客户端虚拟机数量

[client]
script = "benchmark/hyperchain/azolla/script.lua"  # 脚本
type = "flato"                                     # 区块链类型
config = "benchmark/hyperchain/azolla/hyperchain"  # 区块链SDK配置路径
contract = "benchmark/hyperchain/azolla/contract"  # 合约目录路径
plugin = "./hyperchain.so"                         # 插件路径

[client.options] # 客户端选项
sign = "ECDSA"
poll = true