[engine]
rate = 1                            # 速率
duration = "30s"                     # 持续时间
cap = 1                             # 客户端虚拟机数量

[client]
script = "benchmark/javaContract/script.lua"  # 脚本
type = "flato"                           # 区块链类型
config = "benchmark/javaContract/hyperchain"  # 区块链SDK配置路径
contract = "benchmark/javaContract/contract"  # 合约目录路径
args = []                                # 合约参数路径

[client.options] # 客户端选项
keystore = "benchmark/javaContract/keystore"
sign = "ECDSA"