[engine]
rate = 1                                   # 速率
duration = "20s"                           # 持续时间
cap = 1                                    # 客户端虚拟机数量

[client]
script = "benchmark/fabricSacc/script.lua"  # 脚本
type = "fabric"                          # 区块链类型
config = "benchmark/fabricSacc/fabric"  # 区块链SDK配置路径
contract = "github.com/ultramesh/frigate/benchmark/fabricExample/contract"   # 合约目录路径
args = []                               # 合约参数路径

[option]
channel = "mychannel"
initArgs = ["init", "A", "123"]
MSP = true