[engine]
rate = 1                            # 速率
duration = "30s"                    # 持续时间
cap = 1                             # 客户端虚拟机数量

[client]
script = "benchmark/hyperchain/invokeExample/script.lua"  # 脚本
type = "flato"                                            # 区块链类型
config = "benchmark/hyperchain/invokeExample/hyperchain"  # 区块链SDK配置路径
contract = "benchmark/hyperchain/invokeExample/contract"  # 合约目录路径
plugin = "./hyperchain.so"                                # 插件路径

[client.options] # 客户端选项
sign = "SM2"